### ISSUE TITLE
Supply voltage measurement is always 12V on the display

### ISSUE THREAD

**Issue by mgoyard** [Locoduino/LaBox#1]
Pour le 12V :
un bug du bootloader non corrigé laisse GPIO0 HIGH :
https://www.esp32.com/viewtopic.php?t=2205
il peut être contourné avec :
REG_WRITE(GPIO_FUNC0_OUT_SEL_CFG_REG, SIG_GPIO_OUT_IDX);

**Comment by DCC4N** [comment]
The voltage measurement is now handled by IO34 of ESP32, with the version 0.63
A new PCB take this IO34 into account.
see : https://forum.locoduino.org/index.php?topic=922.msg11464#msg11464
